### ISSUE TITLE
[bug report] Does not work with Angular 9.1.0

### ISSUE THREAD

**Issue by nseni** [valor-software/ng2-dragula#994]
**REQUIRED: Before filing a bug report**

Change each `[ ]` to `[x]` when you have done it.

- [x] My issue title starts with `[bug report]`
- [x] I have read the [README](https://github.com/valor-software/ng2-dragula), especially the ['classic blunders' section](https://github.com/valor-software/ng2-dragula#classic-blunders), and the [dragula docs](https://github.com/bevacqua/dragula).
- [x] I have searched through the [`ng2-dragula` issues](https://github.com/valor-software/ng2-dragula/issues) for related problems, including closed issues.
- [x] I have browsed through the [issues labeled "future reference"](https://github.com/valor-software/ng2-dragula/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22future+reference%22) for problems that have been solved before or have a known workaround.
- [x] I am using the latest version of `ng2-dragula`.

**Describe the bug (required)**

After updating Angular to version 9.1.0, ng2-dragula does not work. I'm getting error:
```
main.8c80991e3673d847bd30.js:1 ERROR Error: Uncaught (in promise): ReferenceError: dragulaExpt__default is not defined
ReferenceError: dragulaExpt__default is not defined
```
Error points to file /node_modules/ng2-dragula/dist/fesm2015/ng2-dragula.js, line 2
```
import dragulaExpt__default, {  } from 'dragula';
```

The error happens only in runtime in a production build (`ng build --prod`).

**Comment by nseni** [comment]
https://github.com/angular/angular-cli/issues/17320
