### ISSUE TITLE
Using with Angular-CLI?

### ISSUE THREAD

**Issue by cquillen2003** [valor-software/ng2-dragula#100]
How do you get this to work with Angular-CLI?  After npm installing and importing both dependencies via import, I am getting the following error:

Build error

[DiffingTSCompiler]: Typescript found the following errors:
  node_modules/ng2-dragula/src/app/directives/dragula.directive.ts (10, 15): Cannot find name 'require'.
  node_modules/ng2-dragula/src/app/providers/dragula.provider.ts (1, 15): Cannot find name 'require'.

**Comment by thomasbee** [comment]
We are back to the old problem again: Angular-CLI uses module format system.register, whereas it somehow seems (don't know why) that ng2-dragula requires commonjs. I tried switching angular-cli to commonjs but didn't fully succeed.

**Comment by softgandhi** [comment]
+1
I am also facing the same issue.
Its saying, "require is not defined".

**Comment by NathanWalker** [comment]
@cquillen2003 @thomasbee @softgandhi Please try `1.1.3` just now released. Please let me know if it solves it for you. `require` is no longer used; instead typings for dragula are used via `typings` registry through DefinitelyTyped. You may need to install the `dragula` typings if you run into typescript warnings:
```
typings install dragula --ambient --save
```

However it may just work. 
Please reopen this issue with the error you get if a problem persists.

**Comment by softgandhi** [comment]
@NathanWalker Many thanks for your response.
Now I am facing another issue(s) as it is not resolving the paths for many files:

```
http://localhost:3000/contra/emitter.js 404 (Not Found)
http://localhost:3000/crossvent.js 404 (Not Found)
http://localhost:3000/classes.js 404 (Not Found)
```
I am using system.js in typescript config (I see that you have used commonjs).
It would be great if dependency from multiple files will be reduced.

**Comment by cquillen2003** [comment]
@NathanWalker Thank you for your help.

I no longer get TypeScript errors after upgrading to v1.1.3 and installing the typings, but I now get the following error:

GET http://localhost:4200/ng2-dragula/ng2-dragula 404 (Not Found)     system.src.js:1068

Error: XHR error (404 Not Found) loading http://localhost:4200/ng2-dragula/ng2-dragula
	Error loading http://localhost:4200/ng2-dragula/ng2-dragula as "ng2-dragula/ng2-dragula" from http://localhost:4200/app/components/calendar/day-resource/day-resource.js
    at error (http://localhost:4200/vendor/systemjs/dist/system.src.js:1026:16)
    at XMLHttpRequest.xhr.onreadystatechange [as _onreadystatechange] (http://localhost:4200/vendor/systemjs/dist/system.src.js:1047:13)
    at Zone.run (http://localhost:4200/vendor/angular2/bundles/angular2-polyfills.js:1243:24)
    at XMLHttpRequest.zoneBoundFn (http://localhost:4200/vendor/angular2/bundles/angular2-polyfills.js:1220:26)

**Comment by dancancro** [comment]
I think this is related. I'm trying to use this in an angular-cli project with System.js and getting the following errors:

```
zone.js:461 Unhandled Promise rejection: Error: XHR error (404 Not Found) loading http://localhost:4200/dragula
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:4200/vendor/zone.js/dist/zone.js:769:30)
	    at ZoneDelegate.invokeTask (http://localhost:4200/vendor/zone.js/dist/zone.js:356:38)
	    at Zone.runTask (http://localhost:4200/vendor/zone.js/dist/zone.js:256:48)
	    at XMLHttpRequest.ZoneTask.ZoneTask.cancelFn.invoke (http://localhost:4200/vendor/zone.js/dist/zone.js:423:34)
	Error loading http://localhost:4200/dragula as "dragula" from http://localhost:4200/vendor/ng2-dragula/src/app/directives/dragula.directive.js ; Zone: <root> ; Task: Promise.then ; Value: Error: Error: XHR error (404 Not Found) loading http://localhost:4200/dragula(…)
```

**Comment by dkushner** [comment]
Having the exact same issue as @dancancro on angular@2.0.0-rc.4.
