### ISSUE TITLE
ctorParameters.map is not a function (wrong built solution?)

### ISSUE THREAD

**Issue by montella1507** [valor-software/ng2-dragula#496]
![dragula problem](https://cloud.githubusercontent.com/assets/10418323/21263921/bd0694bc-c399-11e6-9bb9-ef8a63fa3ef2.png)

reflection_capabilities.js:58 Uncaught TypeError: ctorParameters.map is not a function
    at ReflectionCapabilities.parameters (http://localhost:4200/main.bundle.js:56680:45)
    at Reflector.parameters (http://localhost:4200/main.bundle.js:56814:44)
    at CompileMetadataResolver.getDependenciesMetadata (http://localhost:4200/main.bundle.js:34977:54)
    at CompileMetadataResolver.getTypeMetadata (http://localhost:4200/main.bundle.js:34942:26)
    at CompileMetadataResolver.getDirectiveMetadata (http://localhost:4200/main.bundle.js:34717:28)
    at http://localhost:4200/main.bundle.js:34786:49
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/main.bundle.js:34779:44)
    at http://localhost:4200/main.bundle.js:34767:50
    at Array.forEach (native)

**Comment by montella1507** [comment]
Maybe the latest version is not compatible with older CLI than 22-1?

**Comment by paesku** [comment]
To fix this quickly, use version 1.2.2-0

**Comment by montella1507** [comment]
I have to use version older than 2.2.0 because our solutions dont work after that "firebooster" version in IE11,.. Without any error..  Dragula worked for me with version 1.2.2-0 ysterday,.. but i have reinstalled Node_modules today and it throws that error :-/

**Comment by piyushxh** [comment]
Getting the error 

"Uncaught TypeError: ctorParameters.map is not a function
    at ReflectionCapabilities.parameters "

It works well with angular 2.2.3 but not with older versions of angular
My angular version is angular 2.1.1 with  webpack.

Please help need solution in urgent.

Thank you

**Comment by nybroe** [comment]
I am seeing the same issue as  @piyushxh 
I see the issue in the console.
![consoleerror](https://cloud.githubusercontent.com/assets/10866213/21453045/ca799f0a-c90b-11e6-8abc-41a268e69365.PNG)

**Comment by piyushxh** [comment]
ok i found another npm package which is also good 

ng2-dnd
check it out

**Comment by nybroe** [comment]
So just including this in package.json should do the trick?

**Comment by bruno-serfe** [comment]
Hey guys any update on this? this morning I've updated my app

| - angular2-webpack-starter@5.0.5 
| -- protractor@4.0.14 
| -- webdriver-manager@10.3.0

And after those modules are updated the Uncaught TypeError: ctorParameters.map is not a function error appears.

**Comment by lufonius** [comment]
Hi

It seems to work with version 1.2.0. I get the error with version 1.2.2. I'm running angular 2.1.1.

Hope this helps someone. Cheers.

**Comment by LeahPike** [comment]
I'm getting this error running ng2-dragula@1.2.0 as well as ng2-dragula@1.2.2.

**Comment by primaproxima** [comment]
I also have this error using 1.1.17 of ng2-bootstrap.
angular 2.1.2

**Comment by jashatton** [comment]
+1 
I would like to see a fix for this too.

**Comment by leye0** [comment]
It also happens with value-software ng2-popover.

**Comment by valorkin** [comment]
guys please compare your package.json to https://github.com/valor-software/ng2-bootstrap/issues/1497#issuecomment-272823066
and clean install deps
it is not an ng2-dragula issue

**Comment by valorkin** [comment]
https://stackoverflow.com/questions/41285889/ctorparameters-map-is-not-a-function-in-angular2-mdl

**Comment by Darguelles** [comment]
Here you got a few things i did to solve this problem, in my case i was tryin' to deploy my node app on a docker container but the dependencies were bad configured. I hope it helps.
http://stackoverflow.com/a/41733464/4433104

**Comment by azanebrain** [comment]
I've found that this issue is caused by any number of packages expecting the version of Angular Core to be different than what is actually installed.

I was able to figure out the cause of this issue by looking at the error report from `ng build`:

    npm WARN @angular/platform-server@2.4.4 requires a peer of @angular/core@2.4.4 but none was installed.

This helped me realize that one of my packages expected Angular to be at v2.4.4, but I'm using v2.0.1. I updated my package.json to have both packages set to my core version like this:

    "dependencies": {
        "@angular/core": "2.0.1",
        "@angular/platform-server": "2.0.1",
    }

Your issue might not be with @angular/platform-server, but I hope this helps debug it

**Comment by oferh** [comment]
looks like angular compiler cli [issue](https://stackoverflow.com/questions/41285889/ctorparameters-map-is-not-a-function-in-angular2-mdl)

Try to import from `src` folder and not from main if it doesn't work may need to change the minimal Angular version that is supported.
